#!/bin/bash
echo "INSTALLING PIPEWIRE NOW!!!!!!"
echo ""
#Deleting pulseaudio-alsa and pulseaudio-jack packages type yes to both packages
echo "Deleting pulseaudio-alsa and pulseaudio-jack"
sudo pacman -Rs pulseaudio-alsa
sudo pacman -Rs pulseaudio-jack
#Install Pipewire and enable it
echo "Install Pipewire"
sudo pacman -S --needed pipewire-pulse pipewire-alsa pipewire-jack lib32-pipewire lib32-pipewire-jack wireplumber
echo ""
echo "||Enabling Bluetooth Service||"
systemctl --user start pipewire-pulse.service
systemctl --user --now enable pipewire-media-session.service
echo ""
echo "PIPEWIRE IS NOW ENABLE 🎧"
exit
